name: Set secret testing

on:
  push:
    branches:
    - main

jobs:
  set_secrets:
    name: 'set secrets'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      test_env_1: "Hello"
      test_env_2: "from WorkFlow"

    defaults:
      run:
        shell: bash

    steps:
      - id: stage_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.test_env_2 }}

      - name: 'Set secret from test env'
        uses: texas-mcallen-mission/actions-secret-modifier@v2.0.4.2
        with:
          name: 'Test_env'
          value: ${{ steps.stage_case.outputs.uppercase }}
          repository: 'Kapsztajn/actions-set-secret'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          visibility: 'all'